version: "2"
services:
  block-sync:
    container_name: block-sync
    image: trustlab/ixo-blocksync:latest
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://block-sync-db:27017/block-sync
      - CHAIN_URI=BLOCKCHAIN:46657  # Configure this
      - BC_REST=http://REST:1317    # Configure this
      - NODEDID_LIST=
      - IGNORE_EVENTS=message,rewards,proposer_reward,commission,mint,transfer
      # - ONLY_EVENTS=
    restart: always
    ports:
      - "8080:8080"
    links:
      - block-sync-db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  block-sync-db:
    container_name: block-sync-db
    image: mongo
    ports:
      - "27017:27017"



